
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "sent from vs code rest client", 
    "important": true
}
###
GET http://localhost:3001/api/notes/32332
###
PUT http://localhost:3001/api/notes/66a7e224b8c001666c011d54
Content-Type: application/json

{
    "content": "note modified", 
    "important": false
}